name: shell commands

on: [push]

jobs: 
  run-shell-command: 
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "This is a new action - hello world"
      - name: echo multiline script
        run: |
          node -v
          npm -v 
      - name: python commands
        run: |
          import platform
          print(platform.processor())
        shell: python